version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
    timezone: Europe/Brussels
  open-pull-requests-limit: 99
  versioning-strategy: increase
  ignore:
  - dependency-name: "@angular/cli"
    versions:
    - 11.2.3
  - dependency-name: "@angular-devkit/build-angular"
    versions:
    - 0.1102.3
  - dependency-name: "@angular/compiler-cli"
    versions:
    - 11.2.3
