language: generic

git:
  depth: false

dist:
  jammy

cache:
  directories:
  - $HOME/.npm
  - $PWD/node_modules

services:
  - docker

script:
  - docker run -v $PWD:/src -v $HOME/.npm:/root/.npm -v $PWD/node_modules:/src/node_modules -w /src moussavdb/build-nodejs:lts pnpm install
  - docker run -v $PWD:/src -v $HOME/.npm:/root/.npm -v $PWD/node_modules:/src/node_modules -w /src moussavdb/build-nodejs:lts ng build
