language: generic

git:
  depth: false

dist:
  jammy

cache:
  directories:
  - $HOME/.npm
  - $PWD/node_modules

services:
  - docker

before_install:
  - docker login -u="moussavdb" -p="$DOCKER_PASSWORD";
  - docker pull moussavdb/build-nodejs-amd64

script:
  - docker run -v $PWD:/src -v $HOME/.npm:/root/.npm -v $PWD/node_modules:/src/node_modules -w /src moussavdb/build-nodejs-amd64 yarn install
  - docker run -v $PWD:/src -v $HOME/.npm:/root/.npm -v $PWD/node_modules:/src/node_modules -w /src moussavdb/build-nodejs-amd64 ng build --configuration production
